FROM ubuntu:latest

RUN apt update && apt install -y nginx && \
    apt clean && rm -rf /var/lib/apt/lists/*

EXPOSE 80

COPY idk.html var/www/html/idk.html

CMD ["nginx", "-g", "daemon off;"]